# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('ilustracion', models.ImageField(upload_to='examenes/')),
                ('concepto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructivos.Concepto')),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('video', models.FileField(blank=True, upload_to='instructivos-videos/')),
                ('contenido', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructivos.Concepto')),
            ],
            options={
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=140)),
                ('opcion_a', models.CharField(max_length=40)),
                ('opcion_b', models.CharField(max_length=40)),
                ('opcion_c', models.CharField(max_length=40)),
                ('opcion_d', models.CharField(max_length=40)),
                ('opcion_correcta', models.CharField(choices=[('opcion_a', 'A'), ('opcion_b', 'B'), ('opcion_c', 'C'), ('opcion_d', 'D')], default='opcion_a', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(to='instructivos.Pregunta'),
        ),
    ]
