# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('imagen', models.ImageField(upload_to='conceptos/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructivos.Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('imagen', models.ImageField(upload_to='materiales/')),
                ('video', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructivos.Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=140)),
                ('opcion_a', models.CharField(max_length=40)),
                ('opcion_b', models.CharField(max_length=40)),
                ('opcion_c', models.CharField(max_length=40)),
                ('opcion_d', models.CharField(max_length=40)),
                ('opcion_correcta', models.CharField(choices=[('opcion_a', 'A'), ('opcion_b', 'B'), ('opcion_c', 'C'), ('opcion_d', 'D')], default='opcion_a', max_length=8)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructivos.Concepto')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(to='instructivos.Pregunta'),
        ),
    ]
