# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name_plural': 'Examenes'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiales'},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='concepto',
        ),
        migrations.AlterField(
            model_name='concepto',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to='conceptos/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='contenido',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to='materiales/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
