# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0002_auto_20170228_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.CharField(blank=True, default='', help_text='La url donde se encuentra el video para el streaming', max_length=200),
        ),
    ]
