# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0003_auto_20170301_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='concepto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructivos.Concepto'),
        ),
    ]
