# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0003_auto_20170407_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructivo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_1', to='instructivos.Material')),
                ('instructivo_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_10', to='instructivos.Material')),
                ('instructivo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_2', to='instructivos.Material')),
                ('instructivo_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_3', to='instructivos.Material')),
                ('instructivo_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_4', to='instructivos.Material')),
                ('instructivo_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_5', to='instructivos.Material')),
                ('instructivo_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_6', to='instructivos.Material')),
                ('instructivo_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_7', to='instructivos.Material')),
                ('instructivo_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_8', to='instructivos.Material')),
                ('instructivo_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_9', to='instructivos.Material')),
            ],
            options={
                'verbose_name_plural': 'Orden de visualizaci\xf3n de instructivos',
            },
        ),
    ]
