# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0004_auto_20170301_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
