# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0004_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='instructivo_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_1', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_10',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_10', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_2', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_3', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_4', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_5', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_6', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_7',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_7', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_8',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_8', to='instructivos.Material'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instructivo_9',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_9', to='instructivos.Material'),
        ),
    ]
