# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0006_auto_20170418_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='concepto',
        ),
        migrations.AddField(
            model_name='examen',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructivos.Material'),
        ),
    ]
