# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0006_auto_20170302_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, upload_to='instructivos-videos/'),
        ),
    ]
