# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:03
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0007_auto_20170317_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='contenido',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
