# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0009_auto_20170526_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='instructivo_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_11', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_12', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_13', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_14', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_15', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_16', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_17', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_18', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_19', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_20', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_21', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_22', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_23', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_24', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_25', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_26', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_27', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_28', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_29', to='instructivos.Material'),
        ),
        migrations.AddField(
            model_name='orden',
            name='instructivo_30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intructivo_30', to='instructivos.Material'),
        ),
    ]
