# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0009_auto_20170317_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
