# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0011_auto_20170321_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='material',
            name='imagen',
        ),
    ]
