# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructivos', '0007_auto_20170419_0939'),
        ('usuarios', '0003_auto_20170419_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='conceptos_aprobados',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='materiales_aprobados',
            field=models.ManyToManyField(blank=True, to='instructivos.Material'),
        ),
    ]
