# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20170420_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examenaprobado',
            options={'verbose_name': 'Examenes realizados'},
        ),
        migrations.AddField(
            model_name='examenaprobado',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
